# Generated by Django 2.2.7 on 2020-01-27 20:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(default='', max_length=200)),
                ('photo', models.CharField(default='logo.png', max_length=200)),
                ('mobile', models.CharField(default='', max_length=14)),
                ('website', models.URLField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=150)),
                ('overview', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
                ('is_main', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('exp', models.IntegerField(default=0)),
                ('photo', models.CharField(default='avatar.png', max_length=200)),
                ('job_title', models.CharField(default='Freelancer at Freela', max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('mobile', models.CharField(default='', max_length=14)),
                ('website', models.URLField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=150)),
                ('overview', models.TextField(default='Ola! estou no Freela...')),
                ('status', models.BooleanField(default=1)),
                ('is_main', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('deadline', models.IntegerField(default=10)),
                ('overview', models.TextField(default='')),
                ('close_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Budget')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Category')),
                ('employer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Employer')),
                ('experience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.ExperienceLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deadline', models.IntegerField(default=10)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('freelancer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Freelancer')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Project')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('freelancer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Freelancer')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Project')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Status')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='project_skills', to='mozlancers.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Status'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_category', models.IntegerField()),
                ('max_follow', models.IntegerField()),
                ('max_skill', models.IntegerField()),
                ('max_project', models.IntegerField()),
                ('is_customer_chat', models.BooleanField()),
                ('is_premium', models.BooleanField()),
                ('is_notification', models.BooleanField()),
                ('features', models.ManyToManyField(related_name='package_features', to='mozlancers.PackageFeature')),
            ],
        ),
        migrations.CreateModel(
            name='LiterarySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institute', models.CharField(max_length=150)),
                ('freelancer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Freelancer')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Package'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(related_name='freelancer_skills', to='mozlancers.Skill'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Category'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employer',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Package'),
        ),
        migrations.AddField(
            model_name='employer',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Category'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
