# Generated by Django 2.2.7 on 2020-01-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='website',
        ),
    ]
