# Generated by Django 2.2.7 on 2020-01-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0003_freelancer_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='city',
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.TextField(default='logo.png'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='address',
            field=models.CharField(default='Maputo, Moçambique', max_length=150),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='city',
            field=models.CharField(default='Maputo', max_length=150),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='job_title',
            field=models.CharField(default='Freelancer no Freela', max_length=200),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.TextField(default='avatar.png'),
        ),
    ]
