# Generated by Django 2.2.7 on 2020-01-29 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0004_auto_20200129_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_end', models.IntegerField(default=0)),
                ('projects_con', models.IntegerField(default=0)),
                ('proposals_sent', models.IntegerField(default=0)),
                ('customer_reviews', models.IntegerField(default=0)),
                ('violations', models.IntegerField(default=0)),
                ('certifications', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        )
    ]
