# Generated by Django 2.2.7 on 2020-01-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0009_auto_20200131_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozlancers.City'),
        ),
    ]
