# Generated by Django 2.2.7 on 2020-03-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0012_auto_20200303_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaryskills',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='literaryskills',
            name='start_date',
        ),
    ]
