# Generated by Django 2.2.7 on 2020-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0013_auto_20200303_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvite',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='is_exclusive',
            field=models.BooleanField(default=0),
        ),
    ]
