# Generated by Django 2.2.7 on 2020-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0014_auto_20200303_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(default='abc-a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='slug',
            field=models.SlugField(default='abc-a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='abc-a', max_length=150),
            preserve_default=False,
        ),
    ]
