# Generated by Django 2.2.7 on 2020-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0018_auto_20200413_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtype',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
