# Generated by Django 2.2.7 on 2020-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0019_auto_20200413_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='description',
            field=models.CharField(max_length=450),
        ),
    ]
