# Generated by Django 2.2.7 on 2020-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0020_auto_20200414_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='url',
            field=models.CharField(default='google.com', max_length=250),
            preserve_default=False,
        ),
    ]
