# Generated by Django 2.2.7 on 2020-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0021_bugreport_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='mobile',
            field=models.CharField(default='+258', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='mobile',
            field=models.CharField(default='+258', max_length=20),
        ),
    ]
