# Generated by Django 2.2.7 on 2020-04-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0024_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelaGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=150)),
                ('payment_method', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.PaymentMethod')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='payments',
            field=models.ManyToManyField(related_name='freelancer_payments', to='mozlancers.FreelaGateway'),
        ),
    ]
