# Generated by Django 2.2.7 on 2020-04-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0025_auto_20200428_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='payments',
        ),
        migrations.AddField(
            model_name='freelagateway',
            name='freelancer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Freelancer'),
            preserve_default=False,
        ),
    ]
