# Generated by Django 2.2.7 on 2020-05-01 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mozlancers', '0026_auto_20200428_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=250)),
                ('is_completed', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 1, 14, 50, 17, 756871))),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.Package')),
                ('payment_method', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mozlancers.PaymentMethod')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
