# Generated by Django 2.2.7 on 2020-05-01 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0027_auto_20200501_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='reference',
            field=models.IntegerField(db_column='reference', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentpackage',
            name='expire_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 1, 14, 58, 53, 575871)),
        ),
    ]
