# Generated by Django 2.2.7 on 2020-05-01 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0028_auto_20200501_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='reference',
            field=models.IntegerField(default=202001),
        ),
        migrations.AlterField(
            model_name='paymentpackage',
            name='expire_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 1, 15, 0, 13, 960872)),
        ),
    ]
