# Generated by Django 2.2.7 on 2020-05-01 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0029_auto_20200501_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='reference',
        ),
        migrations.AlterField(
            model_name='paymentpackage',
            name='expire_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 1, 15, 15, 8, 24274)),
        ),
    ]
