# Generated by Django 2.2.7 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0031_auto_20200501_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpackage',
            name='mobile',
            field=models.CharField(default=1, editable=False, max_length=14),
            preserve_default=False,
        ),
    ]
