# Generated by Django 2.2.7 on 2020-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozlancers', '0032_paymentpackage_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpackage',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
